name: minifx CI-CD

on:
  push:
    branches:
      - dev

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Actions
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: Run tests
        run: mvn --batch-mode --update-snapshots verify
#  CD:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Generate release
#        run: mkdir staging && cp target/*.jar staging
#        with:
#          name: Package
#          path: staging