# This workflow will build minicp with Maven, and cache/restore any dependencies to improve the workflow execution time
# Before building we have to make sur all test pass then generate release

name: minifx CI-CD

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub Actions
      uses: actions/checkout@v3

    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        architecture: x64
        cache: maven

    - name: Run tests
      run: mvn test
      #mvn --batch-mode --update-snapshots verify
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  CD:
    runs-on: ubuntu-latest
    needs: CI
    steps:
    - name: Checkout GitHub Actions
      uses: actions/checkout@v3
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false
      
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        architecture: x64
        cache: maven
        
    - run: mvn --batch-mode --update-snapshots verify
    - run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging
